name: Cypress Tests

on:
  push:
    branches: main

jobs:
  cypress-run-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          command: npm run test:parallel-1

  cypress-run-2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          command: npm run test:parallel-2

  cypress-run-3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          command: npm run test:parallel-3

  cypress-run-4:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          command: npm run test:parallel-4

  cypress-run-5:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
            
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        start: npm start
        command: npm run test:parallel-5